openapi: "3.0.0"
info:
  version: "0.0.1"
  title: "BariPort API"
  description: "BariPortのAPIです。"
servers:
  - url: "http://localhost:8080"
    description: "このURLはダミーのため、実際には使用しません。"
components:
  schemas:
    Users:
      type: "object"
      properties:
        id:
          type: "string"
        displayName:
          type: "string"
        apiKey:
          type: "string"
    chat_room_participants:
      type: "object"
      properties:
        id:
          type: "integer" # "以降、bigintに置き換え"
        userId:
          type: "integer"
        chatRoomId:
          type: "integer"
    chat_rooms:
      type: "object"
      properties:
        id:
          type: "integer"
        name:
          type: "string"
        type:
          type: "integer"
    messages:
      type: "object"
      properties:
        id:
          type: "integer"
        userId:
          type: "integer"
        chatRoomId:
          type: "integer"
        text:
          type: "string" # "text"
    reviews:
      type: "object"
      properties:
        id:
          type: "integer"
        companyId:
          type: "integer"
        userId:
          type: "integer"
        evaluationScore:
          type: "string" # "本当にstringでいいのか？"
        description:
          type: "string"
    companies:
      type: "object"
      properties:
        id:
          type: "integer"
        name:
          type: "string"
    projects:
      type: "object"
      properties:
        id:
          type: "integer"
        companyId:
          type: "integer"
        name:
          type: "string"
        description:
          type: "string"

security:
  - identity_server_auth:
      - api
paths:
  /test:
    get:
      summary: "Runs a test request against the Identity Server demo API"
      responses:
        401:
          description: "Unauthorized"
        200:
          description: "OK"
